### ISSUE TITLE
multi GPU

### ISSUE THREAD

**Issue by xyz8129** [dkazanc/ToMoBAR#67]
how to run this software with multi-GPU?

**Comment by dkazanc** [comment]
Hi, thanks for the interest. We're currently working on [that](https://github.com/dkazanc/ToMoBAR/pull/66) and will report when it's finished. Should be relatively soon. Cheers

**Comment by xyz8129** [comment]
Thank you very much!

**Comment by dkazanc** [comment]
Hi, the multigpu is now working with the latest version of ToMoBAR. You will need to get the latest ccpi-regulariser (conda install -c ccpi/label/dev ccpi-regulariser ) in order to run iterative reconstruction. Also you will need mpi4py package. 
I've done a couple of demos showing how to run it [here](https://github.com/dkazanc/ToMoBAR/blob/master/Demos/Python/MultiGPU_demo.py) and [here](https://github.com/dkazanc/ToMoBAR/blob/master/Demos/Python/Demo3D_GPU_control.py). Hope it helps
